### ISSUE TITLE
關於新建專案功能問題

### ISSUE THREAD

**Issue by gankrock** [iii-org/deploy-devops#2]
我想詢問，為何新建專案後，會出現無法新增專案問題？
是系統那邊設定有錯誤嗎？
以下是測試機的規格和建置步驟
虛擬化平台：proxmox
硬碟：HDD 200GB(啟用SSD模擬；cache設定Direct sync)
CPU：4插槽 x 4核心(16 core)
記憶體：16GB
ISO版本：IIIDevOps-rke-v1.8.1-202109071351
單台VM，沒有另外做worker設定
安裝設定使用IP沒有使用DNS(正式機才打算申請DNS)

目前是打算架起測試機後，確認功能是否正常
有依照文件做設定
https://hackmd.io/@cori/SyZumKm9d#%E5%9B%9B%E3%80%81%E8%A8%AD%E5%AE%9A%E8%87%AA%E5%8B%95%E6%9B%B4%E6%96%B0%E5%B0%88%E6%A1%88%E7%AF%84%E6%9C%AC
到這裡一切順利，IIIDevOps系統也有順利起來(只有跳過建立worker步驟)
新建幾個測試帳號，在利用sample做測試，結果出現如下圖錯誤

![image](https://user-images.githubusercontent.com/20878830/143399161-5e2b70c0-58b9-41e8-9a4c-178f05879f57.png)
![image](https://user-images.githubusercontent.com/20878830/143399180-1566db69-46f3-4f28-998a-90a38c1756d9.png)

11/26更新
使用IIIDevOps-rke-v1.8.1-202109071351 iso檔案
打掉重建一台，還是無法新建專案
會出現如上圖一樣的錯誤

**Comment by tryweb** [comment]
這問題似乎是範本同步不完整所產生, 常見發生在使用傳統 Disk 的環境, 建議可以使用 root 帳號登入 gitlab 內查看 iiidevops-templates 這 Group 內的範本專案是否和 https://github.com/iiidevops-templates 一致

**Comment by gankrock** [comment]
> 這問題似乎是範本同步不完整所產生, 常見發生在使用傳統 Disk 的環境, 建議可以使用 root 帳號登入 gitlab 內查看 iiidevops-templates 這 Group 內的範本專案是否和 https://github.com/iiidevops-templates 一致

Hi tryweb
後來有回信給Cori了，由於問題是同一個，我還是公司內回信為主好了
然後有附上一些可能的log給你們

**Comment by gankrock** [comment]
> 這問題似乎是範本同步不完整所產生, 常見發生在使用傳統 Disk 的環境, 建議可以使用 root 帳號登入 gitlab 內查看 iiidevops-templates 這 Group 內的範本專案是否和 https://github.com/iiidevops-templates 一致

這個原因不在於範本，而是在於後面的API Server沒有正確起來
主要原因為一開始設定時，並沒有將rancher的node名稱改為iiidevops-k8s
另外裡面有些值是寫死和沒有考慮意外輸入的情況
總之，我直接使用github上的專案，目前是可以成功的情況
